
GET http://0.0.0.0:3001/
###

GET http://localhost:3001/api/products


###


GET http://localhost:3001/api/v1/notes

###

POST https://pdhunt2-production.up.railway.app/api/user
content-type: application/json

{
    "name": "vinay",
     "email":"vinay@gmail.com",
    "password": "vs123"

}

