
GET pdhunt2-production.up.railway.app/
###

GET pdhunt2-production.up.railway.app/api/products


###


GET pdhunt2-production.up.railway.app/api/v1/notes

###

POST pdhunt2-production.up.railway.app/api/user
content-type: application/json

{
    "name": "Monty",
    # "email":"ankit@gmail.com",
    "password": "2654"

}

